### ISSUE TITLE
every time people join a room I get this

### ISSUE THREAD

**Issue by cheese12312421312** [wechaty/puppet-padlocal#110]
(node:6449) UnhandledPromiseRejectionWarning: Error: payload.fromId is null?
    at WechatifiedMessage.talker (/Users/cheese/Test/node_modules/wechaty/dist/src/user/message.js:183:19)
    at WechatifiedMessage.self (/Users/cheese/Test/node_modules/wechaty/dist/src/user/message.js:544:29)
    at Wechaty.onMessage (/Users/cheese/Test/node_modules/wechaty-web-panel/src/handlers/on-message.js:112:23)
(node:6449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)

**Comment by padlocal** [comment]
Fixed
