### ISSUE TITLE
can not download image file

### ISSUE THREAD

**Issue by zhaoshuzi123** [wechaty/puppet-padlocal#113]
For recent several days, we can't download image files.  Is this due to some update of the wechaty ipad protocal?

(node:1045935) UnhandledPromiseRejectionWarning: Error: [tid:59f1a2ec] [12898ms] download file failed:{"host":{"host":"121.51.166.78","port":80},"payload":"qwAAA4hOIJqZdpYAAAAAAAAAAAAAAAADbwAAAAN2ZXIAAAABMQAAAAl3ZWl4aW5udW0AAAAKMjUyNDM1NDk3MAAAAANzZXEAAAABMQAAAA1jbGllbnR2ZXJzaW9uAAAACTQwMjY1NDc1NAAAAAxjbGllbnRvc3R5cGUAAAAMaVBhZCBpT1MxNC4yAAAAB2F1dGhrZXkAAABCMEACAQEEOTA3AgEBAgEBAgSWdpmaAgM9FLwCAQACBG/B9G0CAz0SAAIEsP/0bQIEGygzeQIEYb7f1wIEM95ziAQAAAAAB25ldHR5cGUAAAABMQAAAAxhY2NlcHRkdXBhY2sAAAABMQAAAAZyc2F2ZXIAAAABMQAAAAhyc2F2YWx1ZQAAAIB15vsNM5PJqaC8K83BEl1ivlusiyabLlml28f0mAMvRCjU5mt7r8+QKSkzaczBhYoykiIXmusv4ApDmZqbKM0qpNFODFwCVK1m2QP2Vw0cZfDp6oZ39QqsZdOa6AsPnQwL19reitzoiAShGKX7dCN0meLnRz+j7y45QUsJrx4N+QAAAAhmaWxldHlwZQAAAAEyAAAACnd4Y2hhdHR5cGUAAAABMAAAAAZmaWxlaWQAAAEOMzA4MTg0MDIwMTAwMDQ3ODMwNzYwMjAxMDAwMjA0NWNlNDFhODYwMjAzMmY1NjVkMDIwNDE0YzlhM2I0MDIwNDYxNmZjM2MxMDQ1MTc3Nzg3NTcwNmM2ZjYxNjQ1ZjMxMzczMTM5MzgzMTM0MzYzMjM4Mzk0MDYzNjg2MTc0NzI2ZjZmNmQzMzM3MzEzMTVmMzEzNjMzMzQzNzMxMzQzNTM2MzE1ZjM3Mzg2NjMzMzI2NTM2NjIyZDY2NjMzMTYzMmQzNDMyNjQ2NDJkMzkzNTMyNjUyZDM0MzYzNzMxMzk2NjM0MzAzNDMxMzAzMTAyMDQwMTI1MGEwMjAyMDEwMDA0MDUwMDRjNGQ5OTAwAAAAC2xhc3RyZXRjb2RlAAAAATAAAAAFaXBzZXEAAAABMAAAAA1jbGktcXVpYy1mbGFnAAAAATAAAAAJd3htc2dmbGFnAAAAAAAAAAt3eGF1dG9zdGFydAAAAAEwAAAADWRvd25waWNmb3JtYXQAAAABMQAAAAZvZmZzZXQAAAABMAAAAAtsYXJnZXN2aWRlbwAAAAEwAAAACnNvdXJjZWZsYWcAAAABMA==","unpackaeskey":"3Ay0EuNfuEiK5IYgrA9r5w=="}, received null response
    at Object.<anonymous> (/home/ubuntu/wechaty/padlocal/node_modules/padlocal-client-ts/dist/utils/FileUtils.js:51:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/wechaty/padlocal/node_modules/padlocal-client-ts/dist/utils/FileUtils.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1045935) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1045935) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
G(node:1045935) UnhandledPromiseRejectionWarning: VError: [tid:59f1a2ec] Fail to send socket to:"121.51.166.78:80", data:ab000003884e209a997696000000000000000000000000036f0000000376657200000001310000000977656978696e6e756d0000000a323532343335343937300000000373657100000001310000000d636c69656e7476657273696f6e000000093430323635343735340000000c636c69656e746f73747970650000000c6950616420694f5331342e3200000007617574686b65790000004230400201010439303702010102010102049676999a02033d14bc02010002046fc1f46d02033d12000204b0fff46d02041b283379020461bedfd7020433de73880400000000076e65747479706500000001310000000c61636365707464757061636b00000001310000000672736176657200000001310000000872736176616c75650000008075e6fb0d3393c9a9a0bc2bcdc1125d62be5bac8b269b2e59a5dbc7f498032f4428d4e66b7bafcf9029293369ccc1858a329222179aeb2fe00a43999a9b28cd2aa4d14e0c5c0254ad66d903f6570d1c65f0e9ea8677f50aac65d39ae80b0f9d0c0bd7dade8adce88804a118a5fb74237499e2e7473fa3ef2e39414b09af1e0df90000000866696c657479706500000001320000000a7778636861747479706500000001300000000666696c6569640000010e3330383138343032303130303034373833303736303230313030303230343563653431613836303230333266353635643032303431346339613362343032303436313666633363313034353137373738373537303663366636313634356633313337333133393338333133343336333233383339343036333638363137343732366636663664333333373331333135663331333633333334333733313334333533363331356633373338363633333332363533363632326436363633333136333264333433323634363432643339333533323635326433343336333733313339363633343330333433313330333130323034303132353061303230323031303030343035303034633464393930300000000b6c617374726574636f6465000000013000000005697073657100000001300000000d636c692d717569632d666c616700000001300000000977786d7367666c6167000000000000000b77786175746f737461727400000001300000000d646f776e706963666f726d61740000000131000000066f666673657400000001300000000b6c6172676573766964656f00000001300000000a736f75726365666c61670000000130, after max retry:5: [SocketClient] socket is read-write timeout
    at SocketClient.<anonymous> (/home/ubuntu/wechaty/padlocal/node_modules/padlocal-client-ts/dist/link/SocketClient.js:75:27)
    at Generator.throw (<anonymous>)
    at rejected (/home/ubuntu/wechaty/padlocal/node_modules/padlocal-client-ts/dist/link/SocketClient.js:6:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by treeguard** [comment]
I had the same issue these days

**Comment by treeguard** [comment]
cc @padlocal

**Comment by suntong** [comment]
+1, 

here is the error that I got:

```
Error Error: [tid:ab0718b1] [11212ms] download file failed:{"host":{"host":"203.205.220.38","port":80},"payload":"qwAAA7tOIBSv0akAAAAAAAAAAAAAAAADogAAAAN2ZXIAAAABMQAAAAl3ZWl4aW5udW0AAAAKMjg0OTA5MTM0OAAAAANzZXEAAAACNDcAAAANY2xpZW50dmVyc2lvbgAAAAkzODU4Nzk4NDEAAAAMY2xpZW50b3N0eXBlAAAADGlQYWQgaU9TMTQuMgAAAAdhdXRoa2V5AAAAQjBAAgEBBDkwNwIBAQIBAQIEqdGvFAIDD1JZAgEBAgSQOrkUAgMPW9ECBB/gzcsCBBbgzcsCBGJndmECBFKMaegEAAAAAAduZXR0eXBlAAAAATEAAAAMYWNjZXB0ZHVwYWNrAAAAATEAAAAGcnNhdmVyAAAAATEAAAAIcnNhdmFsdWUAAACAjekj2ICsrdv710X+PIph0x+ZAZAfjKGD84e7SNqmBwRSE12CumUboha9ifBpejO5pxPtmMv74gvJalguE73aHa36M10F2ipTBFmlqfJb0387tG9k+8vuwC/8oVQqVIHHR+Ythxjq/WtS202Ki9jLMIVohYI9ROyZT3VHDZ4coPkAAAAIZmlsZXR5cGUAAAABNAAAAAp3eGNoYXR0eXBlAAAAATAAAAAGZmlsZWlkAAABLDMwODE5MzAyMDEwMDA0ODE4YjMwODE4ODAyMDEwMDAyMDRmMjQ2ZjlkMDAyMDMyZjUzNDEwMjA0MmYyYWZkMmQwMjA0NjIxODYxMDIwNDYzNjE3NTcwNzY2OTY0NjU2ZjVmNjQzNjM0NjYzNTM3MzQ2NTM5MzUzMTMxMzA2MTM2MzY1ZjMxMzYzNDM1MzczNjM0MzgzNjM0NWYzMjMyMzAzMjMyMzUzMTMyMzUzNDMyMzMzMjM5MzUzMTMwNjM2ODYxNzQ3MjZmNmY2ZDVmMzEzNTM2MzM2MTMxNjUzNTJkMzQzMDY1MzYyZDM0MzczNjYxMmQ2MTMyNjQzNzJkMzczNDYyNjQzNzMyNjQzNDM1NjIzMDM2MDIwNDAxMjQwMDA0MDIwMTAwMDQwMAAAAAtsYXN0cmV0Y29kZQAAAAEwAAAABWlwc2VxAAAAATAAAAANY2xpLXF1aWMtZmxhZwAAAAEwAAAACXd4bXNnZmxhZwAAAAAAAAALd3hhdXRvc3RhcnQAAAABMAAAAA1kb3ducGljZm9ybWF0AAAAATEAAAAGb2Zmc2V0AAAAATAAAAALbGFyZ2VzdmlkZW8AAAABMAAAAApzb3VyY2VmbGFnAAAAATAAAAALdmlkZW9mb3JtYXQAAAABMg==","unpackaeskey":"lyyKwD8qnNSgAW1iSmVRjg=="}, received null response caught at msg.toFileBox().
```

I.e., _**received null response**_ caught at msg.**toFileBox()**

The input causing the error is:

```js
WechatifiedMessage {
  _events: [Object: null prototype] {},
  _eventsCount: 0,
  _maxListeners: undefined,
  id: '32645...12541',
  payload: {
    id: '32645...2541',
    timestamp: 1645764881,
    type: 15,
    fromId: 'wxid_l2xu...n22',
    mentionIdList: [],
    roomId: '20...939@chatroom',
    text: '<?xml version="1.0"?>\n' +
      '<msg>\n' +
      '\t<videomsg aeskey="972c8ac03f2a9cd4a0016d624a65518e" cdnvideourl="30819302010004818b3081880201000204f246f9d002032f534102042f2afd2d0204621861020463617570766964656f5f643634663537346539353131306136365f313634353736343836345f323230323235313235343233323935313063686174726f6f6d5f31353633613165352d343065362d343736612d613264372d3734626437326434356230360204012400040201000400" cdnthumbaeskey="972c8ac03f2a9cd4a0016d624a65518e" cdnthumburl="30819302010004818b3081880201000204f246f9d002032f534102042f2afd2d0204621861020463617570766964656f5f643634663537346539353131306136365f313634353736343836345f323230323235313235343233323935313063686174726f6f6d5f31353633613165352d343065362d343736612d613264372d3734626437326434356230360204012400040201000400" length="20794067" playlength="186" cdnthumblength="16567" cdnthumbwidth="304" cdnthumbheight="540" fromusername="wxid_l2xu...pen22" md5="0be01166129a9d21c361bf8ffd4f1406" newmd5="65ed406b2934f592f919f0dbf68f236d" isplaceholder="0" rawmd5="" rawlength="0" cdnrawvideourl="" cdnrawvideoaeskey="" overwritenewmsgid="0" isad="0" />\n' +
      '</msg>\n',
    toId: undefined
  },
  [Symbol(kCapture)]: false
}
```

**Comment by suntong** [comment]
These kind of source/input is not downloadable, so it should be treated instead of throwing exceptions.
