### ISSUE TITLE
Error: unsupported type: 66

### ISSUE THREAD

**Issue by paulhybryant** [wechaty/puppet-padlocal#131]
Got the following error when running the bot:

Error: unsupported type: 66
    at Object.convertMessageType (/root/gitrepo/wechaty-getting-started/node_modules/wechaty-puppet-padlocal/src/padlocal/message-parser/helpers/message.ts:57:13)
    at Object.padLocalMessageToWechaty (/root/gitrepo/wechaty-getting-started/node_modules/wechaty-puppet-padlocal/src/padlocal/schema-mapper/index.ts:23:16)
    at PuppetPadlocal.messageRawPayloadParser (/root/gitrepo/wechaty-getting-started/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1230:12)
    at PuppetPadlocal.messagePayload (/root/gitrepo/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:897:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async WechatifiedMessage.ready (file:///root/gitrepo/wechaty-getting-started/node_modules/wechaty/src/user/message.ts:872:21)
    at async PuppetPadlocal.<anonymous> (file:///root/gitrepo/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:498:15)

**Comment by suntong** [comment]
what's the (sample) input data that causes the above error?

**Comment by paulhybryant** [comment]
It is a pat message
