### ISSUE TITLE
获取room avatar报错

### ISSUE THREAD

**Issue by iyjian** [wechaty/puppet-padlocal#136]
```
wxhook_1  | TypeError [ERR_INVALID_URL]: Invalid URL
wxhook_1  |     at new NodeError (node:internal/errors:371:5)
wxhook_1  |     at onParseError (node:internal/url:536:9)
wxhook_1  |     at new URL (node:internal/url:612:5)
wxhook_1  |     at Function.fromUrl (/node_modules/file-box/dist/src/file-box.js:88:31)
wxhook_1  |     at PuppetPadlocal.roomAvatar (/node_modules/wechaty-puppet-padlocal/dist/puppet-padlocal.js:827:41)
wxhook_1  |     at async Object.exports.create (/libs/Group.js:18:21)
wxhook_1  |     at async refreshGroupInfo (/callbackServer/router/bot.js:32:5)
wxhook_1  |     at async Wechaty.<anonymous> (/callbackServer/router/bot.js:98:3)
```

**Comment by padlocal** [comment]
Fixed, will be released in wechaty-puppet-padlocal@1.11.18
