### ISSUE TITLE
[BUG]有没有稳定可用的版本,ERR PuppetServiceImpl grpcError() start() rejection: The "listener" argument must be of type function. Received undefined

### ISSUE THREAD

**Issue by SusonJohn** [wechaty/puppet-padlocal#139]
Docker image: newly
Docker Container for Wechaty v1.10.4 with Node.js v16.13.0

Client:
wechaty-getting-started@1.11.3 /Users/suson/wechaty-getting-started
├── @chatie/eslint-config@1.0.4
├── @chatie/git-scripts@0.6.2
├── @chatie/tsconfig@4.6.2
├── check-node-version@4.2.1
├── dotenv@11.0.0
├── is-pr@2.0.0
├── qrcode-terminal@0.12.0
├── wechaty-plugin-contrib@1.11.1
├── wechaty-puppet-mock@1.13.4
├── wechaty-puppet-oicq@1.10.2
├── wechaty-puppet-walnut@1.11.7
├── wechaty-puppet-wechat@1.11.12
├── wechaty-puppet-wechat4u@1.11.1
├── wechaty-puppet-whatsapp@1.11.77
├── wechaty-puppet-xp@1.10.17
└── wechaty@1.13.7

运行时报错：
```
07:09:35 VERB PuppetServer start() initializing authorization with token ... done
07:09:35 VERB PuppetServer start() initializing gRPC health service ...
07:09:35 VERB PuppetServer start() initializing gRPC health service ... done
07:09:35 VERB PuppetServer start() initializing TLS CA ...
07:09:35 VERB PuppetServer start() initializing TLS CA ... done
07:09:35 VERB PuppetServer start() initializing gRPC server credentials ...
07:09:35 WARN PuppetServer start() TLS disabled: INSECURE!
07:09:35 VERB PuppetServer start() initializing gRPC server credentials ... done
07:09:35 VERB PuppetServer start() gRPC server starting ...
07:09:35 VERB PuppetServer start() gRPC server starting ... done
07:09:35 VERB StateSwitch <IoClient> active(true) <- (pending)
07:11:17 INFO Io on(jsonrpc): [object Object]
07:11:17 VERB Io on(jsonrpc) send({"id":-9007199254672510,"jsonrpc":"2.0","result":8002})
07:16:11 INFO Io on(jsonrpc): [object Object]
07:16:11 VERB Io on(jsonrpc) send({"id":-9007199254671854,"jsonrpc":"2.0","result":8002})
07:16:11 VERB PuppetServiceImpl event()
07:16:11 VERB EventStreamManager start(stream)
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() for Puppet<PuppetPadlocal>(puppet_padlocal_84790b83d91f4c2aaed0d3d89b03fdb9)
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(friendship) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(login) (listenerCount:2) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(logout) (listenerCount:2) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(message) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-invite) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-join) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-leave) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(room-topic) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(scan) (listenerCount:2) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(dirty) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(dong) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(error) (listenerCount:1) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(heartbeat) (listenerCount:2) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(ready) (listenerCount:2) registering...
07:16:11 VERB EventStreamManager connectPuppetEventToStreamingCall() this.puppet.on(reset) (listenerCount:0) registering...
07:16:11 VERB EventStreamManager onStreamingCallEnd(callback)
07:16:11 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"Wechaty Puppet gRPC stream connect successfully"})
07:16:11 VERB PuppetServiceImpl start()
07:16:11 ERR PuppetServiceImpl grpcError() start() rejection: The "listener" argument must be of type function. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type function. Received undefined
    at checkListener (node:events:128:3)
    at _addListener (node:events:423:3)
    at StateSwitch.addListener (node:events:487:10)
    at PuppetPadlocal._startClient (/wechaty/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:145:20)
    at PuppetPadlocal.start (/wechaty/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:141:16)
    at start (file:///wechaty/node_modules/wechaty-puppet-service/src/server/puppet-implementation.ts:1332:18)
    at Object.start (file:///wechaty/node_modules/wechaty-puppet-service/src/auth/auth-impl-token.ts:49:18)
    at handleUnary (/wechaty/node_modules/@grpc/grpc-js/src/server.ts:896:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
恳求给一下对应的Client端与Server端的版本对应清单，目前使用issue中其他提到的相关解决方案仍无法解决

**Comment by suntong** [comment]
You'll have better chance get it working if starting from here --
https://github.com/padlocal/wechaty-puppet-padlocal-demo/issues/13

Took me quite an effort to get those versions that works (对应的Client端与Server端的版本对应清单). YMMV.

**Comment by padlocal** [comment]
I can not reproduce this issue, @SusonJohn upgrade to wechaty-puppet-padlocal@1.11.15 and to check whether this issue still happens.
