### ISSUE TITLE
ubuntu node16 better-sqlite3 failed

### ISSUE THREAD

**Issue by Ran-Xing** [wechaty/puppet-padlocal#163]
正常的 克隆 https://github.com/wechaty/puppet-padlocal 再安装不会出错
但是 npm install wechaty-puppet-padlocal -g 报错

```log
1315 timing build:link:node_modules/wechaty-puppet-padlocal/node_modules/rc Completed in 8ms
1316 timing build:link:node_modules/wechaty-puppet-padlocal/node_modules/protobufjs Completed in 8ms
1317 timing build:link:node_modules/wechaty-puppet-padlocal/node_modules/rimraf Completed in 7ms
1318 timing build:link:node_modules/wechaty-puppet-padlocal/node_modules/semver Completed in 7ms
1319 timing build:link:node_modules/wechaty-puppet-padlocal/node_modules/uuid Completed in 7ms
1320 timing build:link Completed in 9ms
1321 info run better-sqlite3@7.5.1 install node_modules/wechaty-puppet-padlocal/node_modules/better-sqlite3 prebuild-install || npm run build-release
1322 info run better-sqlite3@7.5.1 install { code: 243, signal: null }
1323 timing reify:rollback:createSparse Completed in 1125ms
1324 timing reify:rollback:retireShallow Completed in 1ms
1325 timing command:install Completed in 12074ms
1326 verbose stack Error: command failed
1326 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/nodejs/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
1326 verbose stack     at ChildProcess.emit (node:events:527:28)
1326 verbose stack     at maybeClose (node:internal/child_process:1092:16)
1326 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
1327 verbose pkgid better-sqlite3@7.5.1
1328 verbose cwd /docker/puppet-padlocal/node_modules
1329 verbose Linux 5.4.0-109-generic
1330 verbose node v16.15.0
1331 verbose npm  v8.8.0
1332 error code 243
1333 error path /usr/local/lib/nodejs/lib/node_modules/wechaty-puppet-padlocal/node_modules/better-sqlite3
1334 error command failed
1335 error command sh -c prebuild-install || npm run build-release
1336 error prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
1337 verbose exit 243
1338 timing npm Completed in 12179ms
1339 verbose unfinished npm timer reify 1652411541711
1340 verbose unfinished npm timer reify:build 1652411552015
1341 verbose unfinished npm timer build 1652411552016
1342 verbose unfinished npm timer build:deps 1652411552017
1343 verbose unfinished npm timer build:run:install 1652411552038
1344 verbose unfinished npm timer build:run:install:node_modules/wechaty-puppet-padlocal/node_modules/better-sqlite3 1652411552038
1345 verbose code 243
1346 error A complete log of this run can be found in:
1346 error     /root/.npm/_logs/2022-05-13T03_12_21_607Z-debug-0.log
```

**Comment by Ran-Xing** [comment]
```
    "wechaty": "^1.19.10",
    "wechaty-puppet": "^1.19.6",
    "wechaty-puppet-padlocal": "^1.11.13"

npm i -g wechaty-puppet-padlocal@1.11.13
```

**Comment by Ran-Xing** [comment]
```bash
wechaty gateway --puppet "wechaty-puppet-padlocal" --port "25000" --token xxxxxxxxxxx --puppet-token xxxxxxxxx
```

```log
11:22:43 INFO Gateway Wechaty version 1.18.1
11:22:43 INFO Gateway Wechaty Puppet Service TOKEN: xxxxxxxxx
11:22:43 INFO Gateway Wechaty Puppet Service Server Port: xxxxxx
11:22:43 INFO Gateway Wechaty Puppet Provider: wechaty-puppet-padlocal
11:22:43 INFO Gateway Wechaty Puppet Provider Token: "xxxxxxxxxxxxxx"
11:22:43 INFO Gateway Registering Wechaty Puppet Token Gateway Service Discovery ...
11:22:44 ERR Puppet resolvePuppetName
Failed to import Wechaty Puppet Provider (WPP) NPM module: "wechaty-puppet-padlocal"
Please make sure:
 1. it has been installed correctly. (run `npm install wechaty-puppet-padlocal` if it doesn't)
 2. "wechaty-puppet-padlocal" is a valid Wechaty Puppet Provider (WPP).

learn more about Wechaty Puppet Providers (WPP) from the official website:
<https://wechaty.js.org/docs/puppet-providers>

11:22:44 ERR IoClient start() exception: Cannot read properties of undefined (reading 'filename')
11:22:44 ERR Gateway Error: TypeError: Cannot read properties of undefined (reading 'filename')
11:22:44 WARN ServiceCtl<Wechaty> stop() found that is stopping/stopped, wait stable ...
11:22:44 WARN ServiceCtl<Wechaty> stop() found that is stopping/stopped, wait stable ... done
/usr/local/lib/nodejs/lib/node_modules/wechaty-puppet-padlocal/node_modules/app-root-path/lib/resolve.js:111
		appRootPath = path.dirname(requireFunction.main.filename);
		                                                ^

TypeError: Cannot read properties of undefined (reading 'filename')
    at resolve (/usr/local/lib/nodejs/lib/node_modules/wechaty-puppet-padlocal/node_modules/app-root-path/lib/resolve.js:111:51)
    at module.exports (/usr/local/lib/nodejs/lib/node_modules/wechaty-puppet-padlocal/node_modules/app-root-path/lib/app-root-path.js:6:20)
    at Object.<anonymous> (/usr/local/lib/nodejs/lib/node_modules/wechaty-puppet-padlocal/node_modules/app-root-path/index.js:4:18)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /usr/local/lib/nodejs/lib/node_modules/wechaty-puppet-padlocal/node_modules/flash-store/bundles/flash-store.umd.js:41:121
```

**Comment by padlocal** [comment]
It seems that you do not have the permission to install at` /root/.npm`

1336 error prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
