### ISSUE TITLE
grpcError() friendshipAdd()

### ISSUE THREAD

**Issue by Ran-Xing** [wechaty/puppet-padlocal#165]
```log
16:12:03 ERR PuppetServiceImpl grpcError() friendshipAdd() rejection: [tid:a57977ff] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a57977ff] wechat bad request error
VError: [tid:a57977ff] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:a57977ff] wechat bad request error
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:527:28)
    at ClientDuplexStreamImpl.emit (node:domain:475:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:689:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

docker 1.19

**Comment by padlocal** [comment]
这个报错的原因是搜索的用户不存在。
