### ISSUE TITLE
onmessage方法中收到文件消息时使用message.toFileBox方法报错

### ISSUE THREAD

**Issue by specialYmx** [wechaty/puppet-padlocal#168]
request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:efd687c1] Can not get message attach, msg.appmsg.appattach.cdnattachurl is required
    at Request._failAllPendingRequest (D:\we\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (D:\we\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:520:28)
    at ClientDuplexStreamImpl.emit (node:domain:475:12)
    at Object.onReceiveStatus (D:\we\puppet-padlocal\node_modules\@grpc\grpc-js\src\client.ts:689:18)
    at Object.onReceiveStatus (D:\we\puppet-padlocal\node_modules\@grpc\grpc-js\src\client-interceptors.ts:424:48)
    at D:\we\puppet-padlocal\node_modules\@grpc\grpc-js\src\call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by padlocal** [comment]
Fixed in https://github.com/wechaty/puppet-padlocal/commit/4588008917171acf0e6d052751333573ecd06db4, please upgrade `wechaty-puppet-padlocal@1.11.5`
