### ISSUE TITLE
 [PadLocalClient] error while syncing onpush: VError: [tid:0c1541a7] 

### ISSUE THREAD

**Issue by 9cat** [wechaty/puppet-padlocal#170]
After successfully  Scanned->Confirmed->Login, 

06:15:31 ERR [PadLocalClient] error while syncing onpush: VError: [tid:0c1541a7] request has been cancelled for reason: CLIENT_ERROR: [tid:0c1541a7] Exception while handling wechat request: longlink reset
    at Request._failAllPendingRequest (/root/projects/wechat-messager/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/root/projects/wechat-messager/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/root/projects/wechat-messager/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/root/projects/wechat-messager/node_modules/padlocal-client-ts/dist/Request.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
06:15:34 INFO [PuppetPadlocal] start login with type: AutoLogin
06:15:40 INFO [PuppetPadlocal] start login with type: QrLogin

**Comment by 9cat** [comment]
(node:1915) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'setMessage' of undefined
    at PuppetPadlocal._onSendMessage (/root/projects/wechat-messager/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1524:27)
    at PuppetPadlocal.messageSendText (/root/projects/wechat-messager/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1004:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at WechatifiedContact.say (/root/projects/wechat-messager/node_modules/wechaty/src/user/contact.ts:417:15)
(node:1915) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)

**Comment by 9cat** [comment]
upgrade to nodejs 16+ , solved.

**Comment by 286163345** [comment]
ERR [PadLocalClient] error while syncing onpush: VError: [tid:80177861] request has been cancelled for reason: CLIENT_ERROR: [tid:80177861] Exception while handling wechat request: longlink reset
    at Request._failAllPendingRequest (/mnt/pkg/puppet-padlocal/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/mnt/pkg/puppet-padlocal/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/mnt/pkg/puppet-padlocal/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/mnt/pkg/puppet-padlocal/node_modules/padlocal-client-ts/dist/Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
^C06:38:10 WARN [PuppetPadlocal] stop() is called on a OFF puppet. await ready(off) and return.

node16.  But he can't seem to.
i try --unhandled-rejections
