### ISSUE TITLE
不支持接收超过20m文件么，调用message.toFileBox()报错

### ISSUE THREAD

**Issue by specialYmx** [wechaty/puppet-padlocal#175]
![image](https://user-images.githubusercontent.com/56808809/173323794-a7e62635-6a31-45ce-bca2-a223da54f9fd.png)

**Comment by specialYmx** [comment]
17:24:28 VERB Message toFileBox()
17:24:28 ERR Config ###########################
17:24:28 ERR Config unhandledRejection: Error: [tid:24b5928a] [555ms] download file failed:{"host":{"host":"183.47.125.247","port":80},"payload":"qwAAAyJOIK4i1KIAAAAAAAAAAAAAAAADCQAAAAN2ZXIAAAABMQAAAAl3ZWl4aW5udW0AAAAKMjczMTgxMTUwMgAAAANzZXEAAAABMQAAAA1jbGllbnR2ZXJzaW9uAAAACTQwMjY1NDc1NAAAAAxjbGllbnRvc3R5cGUAAAAMaVBhZCBpT1MxNC4yAAAAB2F1dGhrZXkAAABCMEACAQEEOTA3AgEBAgEBAgSi1CKuAgM9FLkCAQACBAi4eWoCAy9WXQIE8MijtAIE88ijtAIEYvYcOAIEy4gFGAQAAAAAB25ldHR5cGUAAAABMQAAAAxhY2NlcHRkdXBhY2sAAAABMQAAAAZyc2F2ZXIAAAABMQAAAAhyc2F2YWx1ZQAAAIAqIb9GewBcM1oyhBfPafyMObsrN+A4o2cs8IWiufhcZx4Ec/L5ZrWYm9irUgoiRZHMEtcdx9+sT9DInyjgN668bo0JJmexgfDAewphWEn6dS5G8OYwUUisl5O082lLgeWMhpSeZTOR5Jdq1yckJdFDyO9WKsgdD6TnFyNizXyzqgAAAAhmaWxldHlwZQAAAAE1AAAACnd4Y2hhdHR5cGUAAAABMQAAAAZmaWxlaWQAAACoMzA1MjAyMDEwMDA0NGIzMDQ5MDIwMTAwMDIwNGIzYTQxODRlMDIwMzNkMTFmZDAyMDQ1YjYxNjZiNDAyMDQ2MmE3MDI0MjA0MjQ2NjMyNjQ2MzYyMzYzODM3MmQzNTMxMzYzNDJkMzQzMzMxMzIyZDM5Mzc2NTM4MmQ2MjYyMzI2MjY0MzQzNDM4MzkzODM4MzAwMjA0MDEyNDAwMDcwMjAxMDAwNDAwAAAAC2xhc3RyZXRjb2RlAAAAATAAAAAFaXBzZXEAAAABMAAAAA1jbGktcXVpYy1mbGFnAAAAATAAAAAJd3htc2dmbGFnAAAAAAAAAAt3eGF1dG9zdGFydAAAAAEwAAAADWRvd25waWNmb3JtYXQAAAABMQAAAAZvZmZzZXQAAAABMAAAAAtsYXJnZXN2aWRlbwAAAAEwAAAACnNvdXJjZWZsYWcAAAABMA==","unpackaeskey":"ygz8E9aZhBl7Lr24wcV+gA=="}, retcode: -5103017
    at Object.<anonymous> (C:\Users\ymx\Desktop\getting-started\node_modules\padlocal-client-ts\src\utils\FileUtils.ts:71:11)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ymx\Desktop\getting-started\node_modules\padlocal-client-ts\dist\utils\FileUtils.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) [object Promise]

**Comment by specialYmx** [comment]
[https://github.com/wechaty/puppet-padlocal/issues/13](url)我看到之前有issue有这个关于大文件的，说是只支持20m，需要大文件联系padlocal，但是咋联系啊😂
