### ISSUE TITLE
发文字，经常掉线，需要重新扫码登录

### ISSUE THREAD

**Issue by blueseashore** [wechaty/puppet-padlocal#185]
应用场景：机器人发图文内容
经常性被踢下线，需要重新登录，然后因为被踢下线，提示后边的错误
想请问下，是服务不稳定，还是图文频率不合适

2022/07/24 00:37:01 PuppetService Start()
2022/07/24 00:37:05 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/AdnFABCDNBuGGiy7DDDD","status":2}})
2022/07/24 00:37:05 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"Wechaty Puppet gRPC stream connect successfully"}})
2022/07/24 00:37:12 PuppetService RoomList()
2022/07/24 00:37:12 RoomFactory err:  rpc error: code = Unknown desc = TypeError: Cannot read properties of undefined (reading 'getRoomIds')
    at PuppetPadlocal.roomList (file:///wechaty/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1117:28)
    at roomList (file:///wechaty/node_modules/wechaty-puppet-service/src/server/puppet-implementation.ts:1207:41)
    at Object.roomList (file:///wechaty/node_modules/wechaty-puppet-service/src/auth/auth-impl-token.ts:49:18)
    at handleUnary (/wechaty/node_modules/@grpc/grpc-js/src/server.ts:925:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

还有另外一种错误

rpc error: code = Unknown desc = VError: [tid:5d531870] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:5d531870] wechat bad request error
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:527:28)
    at ClientDuplexStreamImpl.emit (node:domain:475:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:689:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11

**Comment by blueseashore** [comment]
2022/07/24 00:37:01 PuppetService Start()
2022/07/24 00:37:05 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_SCAN payload:{"qrcode":"http://weixin.qq.com/x/AdnFYFzVNBuGGiy7SvX7","status":2}})
2022/07/24 00:37:05 PuppetService onGrpcStreamEvent({type:EVENT_TYPE_HEARTBEAT payload:{"data":"Wechaty Puppet gRPC stream connect successfully"}})
2022/07/24 00:37:12 PuppetService RoomList()
2022/07/24 00:37:12 RoomFactory err:  rpc error: code = Unknown desc = TypeError: Cannot read properties of undefined (reading 'getRoomIds')
    at PuppetPadlocal.roomList (file:///wechaty/node_modules/wechaty-puppet-padlocal/src/puppet-padlocal.ts:1117:28)
    at roomList (file:///wechaty/node_modules/wechaty-puppet-service/src/server/puppet-implementation.ts:1207:41)
    at Object.roomList (file:///wechaty/node_modules/wechaty-puppet-service/src/auth/auth-impl-token.ts:49:18)
    at handleUnary (/wechaty/node_modules/@grpc/grpc-js/src/server.ts:925:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by myhcqgithub** [comment]
ERR [PadLocalClient] error while syncing onpush: VError: [tid:b458bcb4] request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded
同错误。。。。不知为何

**Comment by blueseashore** [comment]
hello，有人吗
