### ISSUE TITLE
wechat stream request: current id is: undefined

### ISSUE THREAD

**Issue by suntong** [wechaty/puppet-padlocal#191]
Anyone get `current id is: undefined` error?

Here are more details:

```
11:07:08 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError: long link init failed: [tid:8d382778] request has been cancelled for reason: CLIENT_ERROR: [tid:8d382778] Exception while handling wechat stream request: stream request must be sent by longlink with id:a3:1711, but current id is: a3:bb9f
11:07:08 WARN [LongLink] longlink reconnect [6] after delay:10000ms
11:07:10 ERR [Request] [tid:e91cf080], padlocal grpc request failed: 3, error: IOError: [tid:e91cf080] Exception while handling wechat stream request: stream request must be sent by longlink with id:a3:cd1a, but current id is: undefined
11:07:10 ERR [Request] [tid:e5381f8f], padlocal grpc request failed: 3, error: IOError: [tid:e5381f8f] Exception while handling wechat stream request: stream request must be sent by longlink with id:a3:c88f, but current id is: undefined
11:07:10 ERR [Request] [tid:ae79e20d], padlocal grpc request failed: 3, error: IOError: [tid:ae79e20d] Exception while handling wechat stream request: stream request must be sent by longlink with id:a3:bb9f, but current id is: undefined
11:07:18 ERR [Request] [tid:0860aa52], padlocal grpc request failed: 3, error: IOError: [tid:0860aa52] Exception while handling wechat stream request: stream request must be sent by longlink with id:a3:c32f, but current id is: undefined
11:07:24 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError: [101.32.118.25:80] longlink socket is closed

```

**Comment by suntong** [comment]
Got it again, and it seems to have nothing to do with *my* script, as I haven't been getting it for two days.

```
10:55:00 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError
: [101.32.118.25:80] longlink socket is closed
10:55:00 WARN [LongLink] longlink reconnect [1] after delay:1000ms
10:55:07 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError
: [101.32.118.25:80] longlink socket is closed
10:55:07 WARN [LongLink] longlink reconnect [2] after delay:1000ms
10:55:09 ERR [Request] [tid:a462d461], padlocal grpc request failed: 3, error: IOError: [tid:a462d461] Exception while handling wechat stream request: stream request must be sent by longlink with id:6a:29af, but current id is: 6a:8fb3                                     
10:55:09 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError: long link init failed: [tid:a462d461] request has been cancelled for reason: CLIENT_ERROR: [tid:a462d461] Exception while handling wechat stream request: stream request must be sent by longlink with id:6a:29af, but current id is: 6a:8fb3
10:55:09 WARN [LongLink] longlink reconnect [3] after delay:2000ms
10:55:16 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError: [101.32.118.25:80] longlink socket is closed
10:55:16 WARN [LongLink] longlink reconnect [4] after delay:3000ms
10:55:24 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError: [101.32.118.25:80] longlink socket is closed
10:55:24 WARN [LongLink] longlink reconnect [5] after delay:5000ms
10:55:26 ERR [Request] [tid:8cc55d3c], padlocal grpc request failed: 3, error: IOError: [tid:8cc55d3c] Exception while handling wechat stream request: stream request must be sent by longlink with id:6a:8fb3, but current id is: undefined
10:55:26 ERR [Request] [tid:5ffb14bb], padlocal grpc request failed: 3, error: IOError: [tid:5ffb14bb] Exception while handling wechat stream request: stream request must be sent by longlink with id:6a:6d63, but current id is: undefined
10:55:26 ERR [Request] [tid:3135c36c], padlocal grpc request failed: 3, error: IOError: [tid:3135c36c] Exception while handling wechat stream request: stream request must be sent by longlink with id:6a:ad89, but current id is: undefined
10:55:26 ERR [Request] [tid:c331daa5], padlocal grpc request failed: 3, error: IOError: [tid:c331daa5] Exception while handling wechat stream request: stream request must be sent by longlink with id:6a:bbab, but current id is: undefined
10:55:35 WARN [LongLink] [101.32.118.25:80] close connection on error,IOError: [101.32.118.25:80] longlink socket is closed
10:55:35 WARN [LongLink] longlink reconnect [6] after delay:10000ms
10:55:37 ERR [Request] [tid:7fc48d67], padlocal grpc request failed: 3, error: IOError: [tid:7fc48d67] Exception while handling wechat stream request: stream request must be sent by longlink with id:6a:2e4c, but current id is: undefined
10:55:54 ERR [Request] [tid:3f9ade00], padlocal grpc request failed: 1, error: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
10:55:54 ERR [PadLocalClient] error while syncing onpush: VError: [tid:3f9ade00] request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Request._failAllPendingRequest (/app/node_modules/padlocal-client-ts/dist/Request.js:265:19)
    at ClientDuplexStreamImpl.<anonymous> (/app/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (node:events:520:28)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:409:28)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:187:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)

```

**Comment by jonnyzheng** [comment]
09:31:31 ERR [PadLocalClient] error while syncing onpush: VError: [tid:5d0f5ac4] request has been cancelled for reason: CLIENT_ERROR: [tid:5d0f5ac4] Exception while handling wechat request: longlink reset
