### ISSUE TITLE
error:check qr code timeout

### ISSUE THREAD

**Issue by nicolos-hetyan** [wechaty/puppet-padlocal#200]
logout之后，重新运行程序，无法展示二维码，显示以下错误信息：

`00:38:50 INFO started. 
00:38:50 INFO [PuppetPadlocal] start login with type: QrLogin
00:42:40 ERR [Request] [tid:b51456cc], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:b51456cc] check qr code timeout
00:42:40 ERR start client failed: VError: [tid:b51456cc] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:b51456cc] check qr code timeout
    at Request._failAllPendingRequest (/Users/admin/Project/wechaty/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at ClientDuplexStreamImpl.<anonymous> (/Users/admin/Project/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:526:28)
    at ClientDuplexStreamImpl.emit (node:domain:475:12)
    at Object.onReceiveStatus (/Users/admin/Project/wechaty/node_modules/@grpc/grpc-js/src/client.ts:693:18)
    at Object.onReceiveStatus (/Users/admin/Project/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
    at /Users/admin/Project/wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:330:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
00:42:41 INFO [PuppetPadlocal] start login with type: QrLogin`

@padlocal

**Comment by nicolos-hetyan** [comment]
"npm": "^8.15.1",
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^1.20.2",
    "wechaty-puppet": "^1.20.2",
    "wechaty-puppet-padlocal": "^1.20.1",
    "axios": "^0.27.2"
node -v 16+
