### ISSUE TITLE
longlink fail 

### ISSUE THREAD

**Issue by TheWithout** [wechaty/puppet-padlocal#208]
I couldn't connect to padlocal, it shows error below

17:10:24 INFO [PadLocalDemo] onScan: Scanned(3)
17:10:33 INFO [PadLocalDemo] onScan: Confirmed(4)
17:10:54 INFO [PadLocalDemo] Contact<XXX> login
17:11:11 ERR [Request] [tid:a42e8ae7], padlocal grpc request failed: 3, error: IOError: [tid:a42e8ae7] Exception while handling wechat request: long link send request timeout
17:11:11 ERR start client failed: VError: [tid:a42e8ae7] request has been cancelled for reason: CLIENT_ERROR: [tid:a42e8ae7] Exception while handling wechat request: long link send request timeout
    at Request._failAllPendingRequest (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at Request.error (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:351:10)
    at Request.<anonymous> (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/dist/Request.js:6:65) 
17:11:11 ERR [Request] [tid:6b8cdea1], padlocal grpc request failed: 3, error: IOError: [tid:6b8cdea1] Exception while handling wechat request: longlink reset
17:11:11 ERR [Request] [tid:801bc837], padlocal grpc request failed: 3, error: IOError: [tid:801bc837] Exception while handling wechat request: longlink reset
17:11:11 ERR [PadLocalClient] error while syncing onpush: VError: [tid:6b8cdea1] request has been cancelled for reason: CLIENT_ERROR: [tid:6b8cdea1] Exception while handling wechat request: longlink reset
    at Request._failAllPendingRequest (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at Request.error (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:351:10)
    at Request.<anonymous> (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/dist/Request.js:6:65)
17:11:11 ERR [PadLocalClient] error while syncing onpush: VError: [tid:801bc837] request has been cancelled for reason: CLIENT_ERROR: [tid:801bc837] Exception while handling wechat request: longlink reset
    at Request._failAllPendingRequest (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:338:15)
    at Request.error (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:351:10)
    at Request.<anonymous> (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/opt/wechaty-puppet-padlocal-demo/node_modules/padlocal-client-ts/dist/Request.js:6:65)
17:11:12 ERR [Request] [tid:4faa0c3b], padlocal grpc request failed: 1, error: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded

**Comment by irmowan** [comment]
+1

**Comment by AisonSu** [comment]
同

**Comment by wenzai007** [comment]
+1 
完全被block了。。。
8 VERB PuppetCacheAgent start()
18:04:58 VERB PuppetCacheMixin start() "dirty" event listener added
18:04:58 VERB ServiceCtl<PuppetServiceMixin> start() super.start() ... done
18:04:58 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ...
18:04:58 INFO
      ============================================================
       Welcome to Wechaty PadLocal puppet!

       - puppet-padlocal version: 0.0.0
       - padlocal-ts-client version: 0.5.3
      ============================================================

18:04:58 SILL [Request] [tid:14399490] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":0}
18:04:58 VERB ServiceCtl<PuppetServiceMixin> start() this.onStart() ... done
18:04:58 SILL StateSwitch <PuppetServiceMixin> active() is pending
18:04:58 VERB StateSwitch <PuppetServiceMixin> active(true) <- (pending)
18:04:58 VERB ServiceCtl<PuppetServiceMixin> start() ... done
18:04:58 VERB PuppetWatchdogAgent start() "heartbeat" event listener added
18:04:58 VERB PuppetWatchdogAgent start() "reset" event listener added
18:04:58 VERB WechatyPuppetMixin start() starting puppet ... done
18:04:58 VERB ServiceCtl<Wechaty> start() super.start() ... done
18:04:58 VERB ServiceCtl<Wechaty> start() this.onStart() ...
18:04:58 VERB Wechaty onStart()
18:04:58 VERB Wechaty <Puppet<PuppetPadlocal>(DemoBot)>(DemoBot) onStart() v1.20.2 is starting...
18:04:58 VERB Wechaty id: 366ba497-134c-4d68-b04f-11c57047d538
18:04:58 VERB Wechaty onStart() ... done
18:04:58 VERB ServiceCtl<Wechaty> start() this.onStart() ... done
18:04:58 SILL StateSwitch <Wechaty> active() is pending
18:04:58 VERB StateSwitch <Wechaty> active(true) <- (pending)
18:04:58 VERB ServiceCtl<Wechaty> start() ... done
18:04:58 INFO [Demo] started.
18:04:58 SILL [Request] [tid:14399490] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"117.184.242.106","port":80},"reconnectimmediately":false,"longlinkhostlistList":[{"host":"117.184.242.106","port":80},{"host":"117.184.242.105","port":80},{"host":"223.166.152.105","port":80},{"host":"223.166.152.106","port":80},{"host":"101.89.15.106","port":80},{"host":"101.89.15.105","port":80}]}}
18:04:58 SILL [Request] [tid:14399490] send event to server, seq:undefined, ack:1, type: 16, payload: {}
18:04:58 SILL [LongLink] update longlink host: [{"host":"117.184.242.106","port":80,"quality":30,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:04:58 SILL [Request] [tid:14399490] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":1}
18:04:58 INFO [PuppetPadlocal] start login with type: AutoLogin
18:04:58 SILL [Request] [tid:14399490] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"5b9fe10b3ccb417e98b7cf27568a7a66","longlinkid":"","initphase":false}}
18:04:58 SILL [LongLink] longlink start connect: 117.184.242.106:80
18:05:08 WARN [LongLink] [] longlink socket connect timeout
18:05:08 SILL [LongLink] adjust host quality:{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30}, connect success:false, host list:[{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:08 WARN [LongLink] [] close connection on error,IOError: longlink socket connect timeout
18:05:08 WARN [LongLink] longlink reconnect [1] after delay:1000ms
18:05:08 ERR [Request] [tid:14399490], padlocal grpc request failed: 3, error: IOError: [tid:14399490] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
18:05:08 ERR start client failed: VError: [tid:14399490] request has been cancelled for reason: CLIENT_ERROR: [tid:14399490] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
    at Request._failAllPendingRequest (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:338:15)
    at Request.error (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:351:10)
    at Request.<anonymous> (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\dist\Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:05:08 SILL [LongLink] [] longlink shutdown
18:05:08 SILL [Request] [tid:3762cf1c] send event to server, seq:1, ack:undefined, type: 15, payload: {"clientstopevent":{}}
18:05:08 SILL [Request] [tid:3762cf1c] receive event from server, seq:0 ack:1, type:16, payload:{}
18:05:10 SILL [Request] [tid:fb32ff12] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
18:05:10 SILL [Request] [tid:fb32ff12] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"117.184.242.106","port":80},"reconnectimmediately":false,"longlinkhostlistList":[{"host":"117.184.242.106","port":80},{"host":"117.184.242.105","port":80},{"host":"223.166.152.105","port":80},{"host":"223.166.152.106","port":80},{"host":"101.89.15.106","port":80},{"host":"101.89.15.105","port":80}]}}
18:05:10 SILL [Request] [tid:fb32ff12] send event to server, seq:undefined, ack:1, type: 16, payload: {}
18:05:10 SILL [LongLink] update longlink host: [{"host":"117.184.242.106","port":80,"quality":30,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:10 SILL [Request] [tid:fb32ff12] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":1}
18:05:10 INFO [PuppetPadlocal] start login with type: AutoLogin
18:05:10 SILL [Request] [tid:fb32ff12] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"cc4f963497fc4c88bedfd83f9af695cf","longlinkid":"","initphase":false}}
18:05:10 SILL [LongLink] longlink start connect: 117.184.242.106:80
18:05:20 WARN [LongLink] [] longlink socket connect timeout
18:05:20 SILL [LongLink] adjust host quality:{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30}, connect success:false, host list:[{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:20 WARN [LongLink] [] close connection on error,IOError: longlink socket connect timeout
18:05:20 WARN [LongLink] longlink reconnect [1] after delay:1000ms
18:05:20 ERR [Request] [tid:fb32ff12], padlocal grpc request failed: 3, error: IOError: [tid:fb32ff12] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
18:05:20 ERR start client failed: VError: [tid:fb32ff12] request has been cancelled for reason: CLIENT_ERROR: [tid:fb32ff12] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
    at Request._failAllPendingRequest (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:338:15)
    at Request.error (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:351:10)
    at Request.<anonymous> (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\dist\Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:05:20 SILL [LongLink] [] longlink shutdown
18:05:20 SILL [Request] [tid:e8b81c21] send event to server, seq:1, ack:undefined, type: 15, payload: {"clientstopevent":{}}
18:05:20 SILL [Request] [tid:e8b81c21] receive event from server, seq:0 ack:1, type:16, payload:{}
18:05:21 SILL [Request] [tid:5bbca5b5] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
18:05:21 SILL [Request] [tid:5bbca5b5] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"117.184.242.106","port":80},"reconnectimmediately":false,"longlinkhostlistList":[{"host":"117.184.242.106","port":80},{"host":"117.184.242.105","port":80},{"host":"223.166.152.105","port":80},{"host":"223.166.152.106","port":80},{"host":"101.89.15.106","port":80},{"host":"101.89.15.105","port":80}]}}
18:05:21 SILL [Request] [tid:5bbca5b5] send event to server, seq:undefined, ack:1, type: 16, payload: {}
18:05:21 SILL [LongLink] update longlink host: [{"host":"117.184.242.106","port":80,"quality":30,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:21 SILL [Request] [tid:5bbca5b5] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":1}
18:05:21 INFO [PuppetPadlocal] start login with type: AutoLogin
18:05:21 SILL [Request] [tid:5bbca5b5] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"a8aab82e52f34fcfbe1df4961d7ef7d8","longlinkid":"","initphase":false}}
18:05:21 SILL [LongLink] longlink start connect: 117.184.242.106:80
18:05:31 WARN [LongLink] [] longlink socket connect timeout
18:05:31 SILL [LongLink] adjust host quality:{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30}, connect success:false, host list:[{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:31 WARN [LongLink] [] close connection on error,IOError: longlink socket connect timeout
18:05:31 WARN [LongLink] longlink reconnect [1] after delay:1000ms
18:05:31 ERR [Request] [tid:5bbca5b5], padlocal grpc request failed: 3, error: IOError: [tid:5bbca5b5] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
18:05:31 ERR start client failed: VError: [tid:5bbca5b5] request has been cancelled for reason: CLIENT_ERROR: [tid:5bbca5b5] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
    at Request._failAllPendingRequest (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:338:15)
    at Request.error (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:351:10)
    at Request.<anonymous> (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\dist\Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:05:31 SILL [LongLink] [] longlink shutdown
18:05:31 SILL [Request] [tid:5beec294] send event to server, seq:1, ack:undefined, type: 15, payload: {"clientstopevent":{}}
18:05:31 SILL [Request] [tid:5beec294] receive event from server, seq:0 ack:1, type:16, payload:{}
18:05:34 SILL [Request] [tid:23438880] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
18:05:34 SILL [Request] [tid:23438880] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"117.184.242.106","port":80},"reconnectimmediately":false,"longlinkhostlistList":[{"host":"117.184.242.106","port":80},{"host":"117.184.242.105","port":80},{"host":"223.166.152.105","port":80},{"host":"223.166.152.106","port":80},{"host":"101.89.15.106","port":80},{"host":"101.89.15.105","port":80}]}}
18:05:34 SILL [Request] [tid:23438880] send event to server, seq:undefined, ack:1, type: 16, payload: {}
18:05:34 SILL [LongLink] update longlink host: [{"host":"117.184.242.106","port":80,"quality":30,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:34 SILL [Request] [tid:23438880] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":1}
18:05:34 INFO [PuppetPadlocal] start login with type: AutoLogin
18:05:34 SILL [Request] [tid:23438880] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"ef83797e77b347149c0fd5bdcfb33722","longlinkid":"","initphase":false}}
18:05:34 SILL [LongLink] longlink start connect: 117.184.242.106:80
18:05:44 WARN [LongLink] [] longlink socket connect timeout
18:05:44 SILL [LongLink] adjust host quality:{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30}, connect success:false, host list:[{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:44 WARN [LongLink] [] close connection on error,IOError: longlink socket connect timeout
18:05:44 WARN [LongLink] longlink reconnect [1] after delay:1000ms
18:05:44 ERR [Request] [tid:23438880], padlocal grpc request failed: 3, error: IOError: [tid:23438880] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
18:05:44 ERR start client failed: VError: [tid:23438880] request has been cancelled for reason: CLIENT_ERROR: [tid:23438880] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
    at Request._failAllPendingRequest (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:338:15)
    at Request.error (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:351:10)
    at Request.<anonymous> (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\dist\Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:05:44 SILL [LongLink] [] longlink shutdown
18:05:44 SILL [Request] [tid:45112c0e] send event to server, seq:1, ack:undefined, type: 15, payload: {"clientstopevent":{}}
18:05:44 SILL [Request] [tid:45112c0e] receive event from server, seq:0 ack:1, type:16, payload:{}
18:05:47 SILL [Request] [tid:72a30f9d] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
18:05:47 SILL [Request] [tid:72a30f9d] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"117.184.242.106","port":80},"reconnectimmediately":false,"longlinkhostlistList":[{"host":"117.184.242.106","port":80},{"host":"117.184.242.105","port":80},{"host":"223.166.152.105","port":80},{"host":"223.166.152.106","port":80},{"host":"101.89.15.106","port":80},{"host":"101.89.15.105","port":80}]}}
18:05:47 SILL [Request] [tid:72a30f9d] send event to server, seq:undefined, ack:1, type: 16, payload: {}
18:05:47 SILL [LongLink] update longlink host: [{"host":"117.184.242.106","port":80,"quality":30,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:47 SILL [Request] [tid:72a30f9d] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":1}
18:05:47 INFO [PuppetPadlocal] start login with type: AutoLogin
18:05:47 SILL [Request] [tid:72a30f9d] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"8b5b28e682a74df481bb9e12700e0aad","longlinkid":"","initphase":false}}
18:05:47 SILL [LongLink] longlink start connect: 117.184.242.106:80
18:05:57 WARN [LongLink] [] longlink socket connect timeout
18:05:57 SILL [LongLink] adjust host quality:{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30}, connect success:false, host list:[{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:05:57 WARN [LongLink] [] close connection on error,IOError: longlink socket connect timeout
18:05:57 WARN [LongLink] longlink reconnect [1] after delay:1000ms
18:05:57 ERR [Request] [tid:72a30f9d], padlocal grpc request failed: 3, error: IOError: [tid:72a30f9d] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
18:05:57 ERR start client failed: VError: [tid:72a30f9d] request has been cancelled for reason: CLIENT_ERROR: [tid:72a30f9d] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
    at Request._failAllPendingRequest (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:338:15)
    at Request.error (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:351:10)
    at Request.<anonymous> (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\dist\Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:05:57 SILL [LongLink] [] longlink shutdown
18:05:57 SILL [Request] [tid:d05aeceb] send event to server, seq:1, ack:undefined, type: 15, payload: {"clientstopevent":{}}
18:05:57 SILL [Request] [tid:d05aeceb] receive event from server, seq:0 ack:1, type:16, payload:{}
18:06:03 SILL [Request] [tid:10fc377c] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
18:06:03 SILL [Request] [tid:10fc377c] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"117.184.242.106","port":80},"reconnectimmediately":false,"longlinkhostlistList":[{"host":"117.184.242.106","port":80},{"host":"117.184.242.105","port":80},{"host":"223.166.152.105","port":80},{"host":"223.166.152.106","port":80},{"host":"101.89.15.106","port":80},{"host":"101.89.15.105","port":80}]}}
18:06:03 SILL [Request] [tid:10fc377c] send event to server, seq:undefined, ack:1, type: 16, payload: {}
18:06:03 SILL [LongLink] update longlink host: [{"host":"117.184.242.106","port":80,"quality":30,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:06:03 SILL [Request] [tid:10fc377c] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":1}
18:06:03 INFO [PuppetPadlocal] start login with type: AutoLogin
18:06:03 SILL [Request] [tid:10fc377c] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"71bf2a59ab8a4ad3a9dbad1d3945e796","longlinkid":"","initphase":false}}
18:06:03 SILL [LongLink] longlink start connect: 117.184.242.106:80
18:06:13 WARN [LongLink] [] longlink socket connect timeout
18:06:13 SILL [LongLink] adjust host quality:{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30}, connect success:false, host list:[{"host":"117.184.242.106","port":80,"quality":28,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:06:13 WARN [LongLink] [] close connection on error,IOError: longlink socket connect timeout
18:06:13 WARN [LongLink] longlink reconnect [1] after delay:1000ms
18:06:13 ERR [Request] [tid:10fc377c], padlocal grpc request failed: 3, error: IOError: [tid:10fc377c] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
18:06:13 ERR start client failed: VError: [tid:10fc377c] request has been cancelled for reason: CLIENT_ERROR: [tid:10fc377c] Exception while handling wechat request: longlink fail to connect: longlink socket connect timeout
    at Request._failAllPendingRequest (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:338:15)
    at Request.error (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:351:10)
    at Request.<anonymous> (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\src\Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (E:rootfolder\puppet-padlocal\node_modules\padlocal-client-ts\dist\Request.js:6:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:06:13 SILL [LongLink] [] longlink shutdown
18:06:13 SILL [Request] [tid:0584c315] send event to server, seq:1, ack:undefined, type: 15, payload: {"clientstopevent":{}}
18:06:13 SILL [Request] [tid:0584c315] receive event from server, seq:0 ack:1, type:16, payload:{}
18:06:23 SILL [Request] [tid:1244f2f5] send event to server, seq:1, ack:undefined, type: 200, payload: {"policy":1}
18:06:23 SILL [Request] [tid:1244f2f5] receive event from server, seq:1 ack:0, type:15, payload:{"longlinkupdateevent":{"longlinkhost":{"host":"117.184.242.106","port":80},"reconnectimmediately":false,"longlinkhostlistList":[{"host":"117.184.242.106","port":80},{"host":"117.184.242.105","port":80},{"host":"223.166.152.105","port":80},{"host":"223.166.152.106","port":80},{"host":"101.89.15.106","port":80},{"host":"101.89.15.105","port":80}]}}
18:06:23 SILL [Request] [tid:1244f2f5] send event to server, seq:undefined, ack:1, type: 16, payload: {}
18:06:23 SILL [LongLink] update longlink host: [{"host":"117.184.242.106","port":80,"quality":30,"initialQuality":30},{"host":"117.184.242.105","port":80,"quality":25,"initialQuality":25},{"host":"223.166.152.105","port":80,"quality":20,"initialQuality":20},{"host":"223.166.152.106","port":80,"quality":15,"initialQuality":15},{"host":"101.89.15.106","port":80,"quality":10,"initialQuality":10},{"host":"101.89.15.105","port":80,"quality":5,"initialQuality":5}]
18:06:23 SILL [Request] [tid:1244f2f5] receive event from server, seq:0 ack:0, type:201, payload:{"status":0,"logintype":1}
18:06:23 INFO [PuppetPadlocal] start login with type: AutoLogin
18:06:23 SILL [Request] [tid:1244f2f5] receive event from server, seq:2 ack:0, type:10, payload:{"longlinkrequest":{"messageid":"e03d9572af0246b79e6d66cf4275a576","longlinkid":"","initphase":false}}
18:06:23 SILL [LongLink] longlink start connect: 117.184.242.106:80
