### ISSUE TITLE
登入后,发送消息,就会退出登录

### ISSUE THREAD

**Issue by quboqin** [wechaty/puppet-padlocal#216]
申请了一个临时的Token
之前还算稳定,昨天一直有问题,可以登入成功,但是发送消息就报: Exception while handling wechat request: longlink reset
完整的日志如下:
0|chat  | 01:58:46 ERR [Request] [tid:e8df3e0a], padlocal grpc request failed: 3, error: IOError: [tid:e8df3e0a] Exception while handling wechat request: longlink reset
0|chat  | 01:58:46 ERR [PadLocalClient] error while syncing onpush: VError: [tid:e8df3e0a] request has been cancelled for reason: CLIENT_ERROR: [tid:e8df3e0a] Exception while handling wechat request: longlink reset
0|chat  |     at Request._failAllPendingRequest (/root/wechaty-chatgpt/node_modules/padlocal-client-ts/dist/Request.js:265:19)
0|chat  |     at Request.error (/root/wechaty-chatgpt/node_modules/padlocal-client-ts/dist/Request.js:275:14)
0|chat  |     at Request.<anonymous> (/root/wechaty-chatgpt/node_modules/padlocal-client-ts/dist/Request.js:159:30)
0|chat  |     at Generator.throw (<anonymous>)
0|chat  |     at rejected (/root/wechaty-chatgpt/node_modules/padlocal-client-ts/dist/Request.js:6:65)
0|chat  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

0|chat  | 01:59:46 ERR [Request] [tid:af994e39], padlocal grpc request failed: 1, error: Error: 4 DEADLINE_EXCEEDED: Deadline exceeded
0|chat  | 01:59:46 ERR [PadLocalClient] error while syncing onpush: VError: [tid:af994e39] request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded
0|chat  |     at Request._failAllPendingRequest (/root/wechaty-chatgpt/node_modules/padlocal-client-ts/dist/Request.js:265:19)
0|chat  |     at ClientDuplexStreamImpl.<anonymous> (/root/wechaty-chatgpt/node_modules/padlocal-client-ts/dist/Request.js:56:18)
0|chat  |     at ClientDuplexStreamImpl.emit (node:events:513:28)
0|chat  |     at Object.onReceiveStatus (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/client.js:410:28)
0|chat  |     at Object.onReceiveStatus (/root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
0|chat  |     at /root/wechaty-chatgpt/node_modules/@grpc/grpc-js/build/src/resolving-call.js:93:78
0|chat  |     at processTicksAndRejections (node:internal/process/task_queues:77:11)
0|chat  |     at runNextTicks (node:internal/process/task_queues:64:3)
0|chat  |     at listOnTimeout (node:internal/timers:533:9)
0|chat  |     at process.processTimers (node:internal/timers:507:7)

**Comment by xllusion-dong** [comment]
Token过期了
