### ISSUE TITLE
text message send is success,when send MiniProgram message get an error

### ISSUE THREAD

**Issue by jschenqiang** [wechaty/puppet-padlocal#227]
![image](https://user-images.githubusercontent.com/13410071/222310502-49127c3e-d4be-4ff3-bbb2-6bc7c9f1ea3b.png)
![image](https://user-images.githubusercontent.com/13410071/222310808-9cbad188-e6b7-4b79-9ca6-5670b52c7317.png)

**Comment by jschenqiang** [comment]
09:53:20 ERR [Request] [tid:79161c42], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:79161c42] wechat bad request error
VError: [tid:79161c42] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:79161c42] wechat bad request error
    at Request._failAllPendingRequest (D:\project\wechaty\wechat-bot-main\wechat-bot-main\node_modules\padlocal-client-ts\dist\Request.js:265:19)
    at ClientDuplexStreamImpl.<anonymous> (D:\project\wechaty\wechat-bot-main\wechat-bot-main\node_modules\padlocal-client-ts\dist\Request.js:56:18)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at Object.onReceiveStatus (D:\project\wechaty\wechat-bot-main\wechat-bot-main\node_modules\@grpc\grpc-js\build\src\client.js:410:28)
    at Object.onReceiveStatus (D:\project\wechaty\wechat-bot-main\wechat-bot-main\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)
    at D:\project\wechaty\wechat-bot-main\wechat-bot-main\node_modules\@grpc\grpc-js\build\src\resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
