### ISSUE TITLE
request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded,出一直现超时

### ISSUE THREAD

**Issue by Ceferr** [wechaty/puppet-padlocal#228]
12:47:28 ERR [PadLocalClient] error while syncing onpush: VError: [tid:1638475f] request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (events.js:400:28)
    at ClientDuplexStreamImpl.emit (domain.js:470:12)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client.ts:670:18)
    at Object.onReceiveStatus (/wechaty/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /wechaty/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
12:47:30 VERB EventStreamManager grpcEmit(EVENT_TYPE_HEARTBEAT[1], {"data":"heartbeat@padlocal"})
12:47:36 ERR Config ###########################
12:47:36 ERR Config unhandledRejection: VError: longlink socket connect timeout
    at Timeout.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:365:25)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) [object Promise]
12:47:36 ERR Config ###########################
12:47:36 ERR Config process.on(unhandledRejection) promise.catch(longlink socket connect timeout)
Config IOError [VError]: longlink socket connect timeout
    at Timeout.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/link/WeChatLongLinkProxy.ts:365:25)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  jse_shortmsg: 'longlink socket connect timeout',
  jse_info: {}
}
(node:41) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 19)

12:33:44 ERR [PadLocalClient] error while syncing after longlink connected: VError: [tid:c84c1cea] request has been cancelled for reason: CLIENT_ERROR: [tid:c84c1cea] Exception while handling wechat request: long link send request timeout
    at Request._failAllPendingRequest (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at Request.error (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:347:10)
    at Request.<anonymous> (/wechaty/node_modules/padlocal-client-ts/src/Request.ts:221:16)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/padlocal-client-ts/dist/Request.js:6:65)

有人遇到过这种情况吗，在centos上docker部署，过一段时间就会超时

**Comment by metanoia1989** [comment]
同遇到这种问题啊

**Comment by joephon** [comment]
+1

**Comment by irmowan** [comment]
+1 AutoLogin经常会超时

**Comment by shiyeling** [comment]
遇到类似的问题，希望有一个能捕捉这种异常并进行处理的方式

**Comment by AisonSu** [comment]
我也是
