### ISSUE TITLE
重新登陆失败

### ISSUE THREAD

**Issue by zscorpio** [wechaty/puppet-padlocal#233]
错误日志如下, 之前登录正常, 昨晚掉了之后, 今天重登失败
```
09:31:24 ERR [Request] [tid:0f9e62f4], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:0f9e62f4] wechat bad request error: 你已退出微信
09:31:24 ERR start client failed: VError: [tid:0f9e62f4] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:0f9e62f4] wechat bad request error: 你已退出微信
    at Request._failAllPendingRequest (node_modules/padlocal-client-ts/dist/Request.js:265:19)
    at ClientDuplexStreamImpl.<anonymous> (node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (node:events:527:28)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:410:28)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) 
```

**Comment by zhaoeryu** [comment]
同样的错误

**Comment by Hzqi** [comment]
不会是padlocal被封禁了吧？我这边是昨晚两点开始出这个问题，换了账号登陆也不行

**Comment by nosun** [comment]
07:09:02 INFO WechatyPluginContrib EventLogger heartbeat: heartbeat@padlocal
07:09:17 INFO WechatyPluginContrib EventLogger heartbeat: heartbeat@padlocal
VError: [tid:111f1347] request has been cancelled for reason: SERVER_ERROR: 4 DEADLINE_EXCEEDED: Deadline exceeded
    at Request._failAllPendingRequest (/nodejs/bot/node_modules/padlocal-client-ts/src/Request.ts:334:15)
    at ClientDuplexStreamImpl.<anonymous> (/nodejs/bot/node_modules/padlocal-client-ts/src/Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at ClientDuplexStreamImpl.emit (node:domain:489:12)
    at Object.onReceiveStatus (/nodejs/bot/node_modules/@grpc/grpc-js/src/client.ts:673:18)
    at Object.onReceiveStatus (/nodejs/bot/node_modules/@grpc/grpc-js/src/client-interceptors.ts:392:48)
    at /nodejs/bot/node_modules/@grpc/grpc-js/src/call-stream.ts:299:24
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
07:10:28 INFO WechatyPluginContrib EventLogger heartbeat: heartbeat@padlocal

**Comment by zhaoeryu** [comment]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/49333146/228448464-f3c4a94a-9ac3-460f-836d-86f6b7e44bfb.png">

**Comment by zhaoeryu** [comment]
<img width="1348" alt="image" src="https://user-images.githubusercontent.com/49333146/228449585-9ea35176-0e76-4a1b-b88d-9872220e205b.png">

**Comment by nosun** [comment]
我测试已经恢复了，可能和 @zhaoeryu 发的这个事故有关系～

**Comment by zhaoeryu** [comment]
> <img alt="image" width="1348" src="https://user-images.githubusercontent.com/49333146/228449585-9ea35176-0e76-4a1b-b88d-9872220e205b.png">

我昨天晚上5点50左右恢复正常
