### ISSUE TITLE
你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面

### ISSUE THREAD

**Issue by 1061168609** [wechaty/puppet-padlocal#301]
09:31:49 ERR [Request] [tid:3fa798de], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:3fa798de] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。
09:31:49 ERR start client failed: VError: [tid:3fa798de] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:3fa798de] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版载页面。
    at Request._failAllPendingRequest (D:\phpstudy_pro\WWW\puppet-padlocal-main\puppet-padlocal-main\node_modules\_padlocal-client-ts@0.5.3@padlocal-client-ts\src\Request.ts:338:15)
    at ClientDuplexStreamImpl.<anonymous> (D:\phpstudy_pro\WWW\puppet-padlocal-main\puppet-padlocal-main\node_modules\_padlocal-client-ts@0.5.3@padlocal-client-ts\src\Request.ts:82:12)
    at ClientDuplexStreamImpl.emit (node:events:513:28)
    at ClientDuplexStreamImpl.emit (node:domain:489:12)
    at Object.onReceiveStatus (D:\phpstudy_pro\WWW\puppet-padlocal-main\puppet-padlocal-main\node_modules\_@grpc_grpc-js@1.7.3@@grpc\grpc-js\src\client.ts:703:18)
    at Object.onReceiveStatus (D:\phpstudy_pro\WWW\puppet-padlocal-main\puppet-padlocal-main\node_modules\_@grpc_grpc-js@1.7.3@@grpc\grpc-js\src\client-interceptors.ts:424:48)
    at D:\phpstudy_pro\WWW\puppet-padlocal-main\puppet-padlocal-main\node_modules\_@grpc_grpc-js@1.7.3@@grpc\grpc-js\src\call-stream.ts:334:24
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
09:31:51 INFO [PuppetPadlocal] start login with type: QrLogin

**Comment by akrio714** [comment]
+1

**Comment by YizheShang** [comment]
同样的问题。

**Comment by youguanfan** [comment]
+1

**Comment by youguanfan** [comment]
为啥客服也不回复消息

**Comment by wanghang123** [comment]
目前都是这个问题。
