### ISSUE TITLE
在微信群里使用拍一拍报错

### ISSUE THREAD

**Issue by biofer** [wechaty/puppet-padlocal#89]
你好。
目前开发环境是`padlocal` +`python-wechaty` .
在1对1对话中使用`拍一拍`可以返回做的这个动作的人，但是在微信群里，使用`拍一拍`就没办法返回这个动作的人。
烦请您看一看。
在`python-wechaty` 中提交的https://github.com/wechaty/python-wechaty/issues/248#issue-970924957

- docker容器中的报错
```
00:57:46 VERB [Request] [tid:1d76a5af] receive event from server, seq:0 ack:1, type:85, payload:{"messageList":[{"type":0,"messageid":"ffb424ea35164f40a3eb022a438f21d9"}]}
00:57:46 VERB [Request] [tid:c5a0517e] send event to server, seq:undefined, ack:1, type: 11, payload: {"longlinkresponse":{}}
00:57:46 VERB [Request] [tid:c5a0517e] receive event from server, seq:0 ack:1, type:101, payload:{"payload":{"contactList":[],"messageList":[{"id":"2614807138110118776","type":10002,"createtime":1629421065,"fromusername":"21307892424@chatroom","tousername":"wxid_stk85kxmgmgj22","content":"21307892424@chatroom:\n<sysmsg type=\"pat\">\n<pat>\n  <fromusername>dingwei10392</fromusername>\n  <chatusername>21307892424@chatroom</chatusername>\n  <pattedusername>wxid_stk85kxmgmgj22</pattedusername>\n  <patsuffix><![CDATA[]]></patsuffix>\n  <patsuffixversion>0</patsuffixversion>\n\n\n\n\n  <template><![CDATA[\"${dingwei10392}\" 拍了拍我]]></template>\n\n\n\n\n</pat>\n</sysmsg>","pushcontent":"","binarypayload":"","atList":[]}]}}
00:57:46 VERB [PadLocalClient] on push notification, contact count:0, message count:1
00:57:46 VERB [PuppetPadlocal] on push original message: {"id":"2614807138110118776","type":10002,"createtime":1629421065,"fromusername":"213*******@chatroom","tousername":"wxid_********","content":"213*******@chatroom:\n<sysmsg type=\"pat\">\n<pat>\n  <fromusername>di********</fromusername>\n  <chatusername>********@chatroom</chatusername>\n  <pattedusername>wxid_******</pattedusername>\n  <patsuffix><![CDATA[]]></patsuffix>\n  <patsuffixversion>0</patsuffixversion>\n\n\n\n\n  <template><![CDATA[\"${din*******}\" 拍了拍我]]></template>\n\n\n\n\n</pat>\n</sysmsg>","pushcontent":"","binarypayload":"","atList":[]}
00:57:46 VERB [PuppetPadlocal] 0a133236313438303731333831313031313837373610924e1889fcfb8806221432313330373839323432344063686174726f6f6d2a13777869645f73746b38356b786d676d676a323232f00232313330373839323432344063686174726f6f6d3a0a3c7379736d736720747970653d22706174223e0a3c7061743e0a20203c66726f6d757365726e616d653e64696e6777656931303339323c2f66726f6d757365726e616d653e0a20203c63686174757365726e616d653e32313330373839323432344063686174726f6f6d3c2f63686174757365726e616d653e0a20203c706174746564757365726e616d653e777869645f73746b38356b786d676d676a32323c2f706174746564757365726e616d653e0a20203c7061747375666669783e3c215b43444154415b5d5d3e3c2f7061747375666669783e0a20203c70617473756666697876657273696f6e3e303c2f70617473756666697876657273696f6e3e0a0a0a0a0a20203c74656d706c6174653e3c215b43444154415b22247b64696e6777656931303339327d2220e68b8de4ba86e68b8de688915d5d3e3c2f74656d706c6174653e0a0a0a0a0a3c2f7061743e0a3c2f7379736d73673e
00:57:46 VERB Message static load(2614807138110118776)
00:57:46 VERB Message constructor(2614807138110118776) for class WechatifiedMessage
00:57:46 VERB Message ready()
00:57:46 VERB Puppet messagePayload(2614807138110118776)
00:57:46 VERB EventStreamManager grpcEmit(EVENT_TYPE_MESSAGE[2], {"messageId":"2614807138110118776"})
00:57:46 VERB Room ready()
00:57:46 ERR Config ###########################
00:57:46 ERR Config unhandledRejection: Error: payload.fromId is null?
    at WechatifiedMessage.talker (/wechaty/src/user/message.ts:268:13)
    at WechatifiedMessage.toString (/wechaty/src/user/message.ts:206:12)
    at String.replace (<anonymous>)
    at sprintf (/wechaty/node_modules/brolog/bundles/brolog.umd.js:374:21)
    at Brolog.log (/wechaty/node_modules/brolog/dist/brolog.js:169:1)
    at Brolog.verbose (/wechaty/node_modules/brolog/dist/brolog.js:278:1)
    at IoClient.onMessage (/wechaty/src/io-client.ts:200:9)
    at Wechaty.<anonymous> (/wechaty/src/io-client.ts:151:35)
    at Wechaty.emit (events.js:326:22)
    at Wechaty.EventEmitter.emit (domain.js:483:12)
    at PuppetPadlocal.<anonymous> (/wechaty/src/wechaty.ts:483:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) [object Promise]
00:57:46 ERR Config ###########################
00:57:46 ERR Config ###########################
00:57:46 ERR Config unhandledRejection: Error: payload.fromId is null?
    at WechatifiedMessage.talker (/wechaty/src/user/message.ts:268:13)
    at WechatifiedMessage.toString (/wechaty/src/user/message.ts:206:12)
    at String.replace (<anonymous>)
    at sprintf (/wechaty/node_modules/brolog/bundles/brolog.umd.js:374:21)
    at Brolog.log (/wechaty/node_modules/brolog/dist/brolog.js:169:1)
    at Brolog.verbose (/wechaty/node_modules/brolog/dist/brolog.js:278:1)
    at IoClient.onMessage (/wechaty/src/io-client.ts:200:9)
    at Wechaty.<anonymous> (/wechaty/src/io-client.ts:151:35)
    at Wechaty.emit (events.js:326:22)
    at Wechaty.EventEmitter.emit (domain.js:483:12)
    at PuppetPadlocal.<anonymous> (/wechaty/src/wechaty.ts:483:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) [object Promise]
00:57:46 ERR Config ###########################
00:57:46 ERR Config process.on(unhandledRejection) promise.catch(payload.fromId is null?)
Config Error: payload.fromId is null?
    at WechatifiedMessage.talker (/wechaty/src/user/message.ts:268:13)
    at WechatifiedMessage.toString (/wechaty/src/user/message.ts:206:12)
    at String.replace (<anonymous>)
    at sprintf (/wechaty/node_modules/brolog/bundles/brolog.umd.js:374:21)
    at Brolog.log (/wechaty/node_modules/brolog/dist/brolog.js:169:1)
    at Brolog.verbose (/wechaty/node_modules/brolog/dist/brolog.js:278:1)
    at IoClient.onMessage (/wechaty/src/io-client.ts:200:9)
    at Wechaty.<anonymous> (/wechaty/src/io-client.ts:151:35)
    at Wechaty.emit (events.js:326:22)
    at Wechaty.EventEmitter.emit (domain.js:483:12)
    at PuppetPadlocal.<anonymous> (/wechaty/src/wechaty.ts:483:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
00:57:46 ERR Config process.on(unhandledRejection) promise.catch(payload.fromId is null?)
Config Error: payload.fromId is null?
    at WechatifiedMessage.talker (/wechaty/src/user/message.ts:268:13)
    at WechatifiedMessage.toString (/wechaty/src/user/message.ts:206:12)
    at String.replace (<anonymous>)
    at sprintf (/wechaty/node_modules/brolog/bundles/brolog.umd.js:374:21)
    at Brolog.log (/wechaty/node_modules/brolog/dist/brolog.js:169:1)
    at Brolog.verbose (/wechaty/node_modules/brolog/dist/brolog.js:278:1)
    at IoClient.onMessage (/wechaty/src/io-client.ts:200:9)
    at Wechaty.<anonymous> (/wechaty/src/io-client.ts:151:35)
    at Wechaty.emit (events.js:326:22)
    at Wechaty.EventEmitter.emit (domain.js:483:12)
    at PuppetPadlocal.<anonymous> (/wechaty/src/wechaty.ts:483:18)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:42) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 64)
```

**Comment by fangmuke** [comment]
#64

**Comment by padlocal** [comment]
Fixed in `wechaty-puppet-padlocal@1.11.18`
